spring.application.name=microSpring

# MongoDB (Docker on localhost)
spring.data.mongodb.uri=mongodb://localhost:27017/microspring

# Auth0 OAuth2 Configuration
spring.security.oauth2.client.registration.auth0.client-id=FntL0IgKchH9ug72Cjv1jOnp47ppQAkw
spring.security.oauth2.client.registration.auth0.client-secret=yvF-D_t814hYFshK4Da_mgC2GzsN94Oru4OEehtig2-jz8l2XhDlzKMXe6LIm8ew
spring.security.oauth2.client.registration.auth0.scope=openid,profile,email
spring.security.oauth2.client.provider.auth0.issuer-uri=https://dev-cq55f1b8glsxzhkg.us.auth0.com/
